### ISSUE TITLE
The height of btn is too low for summary

### ISSUE THREAD

**Issue by peijunz** [alexandrevicenzi/Flex#107]
In the file https://github.com/alexandrevicenzi/Flex/blob/master/static/stylesheet/style.less#L267
```css
a.btn {
	  background-color: @btn-bg;
	  padding: .6em .6em;
	  font-size: .8em;
	  line-height: 1;
	  color: @btn-text-color;
	  text-align: center;
	  white-space: nowrap;
	  vertical-align: baseline;
	  border-radius: .25em;
	}
```

The problem is that although there is a `padding: .6em .6em;`, the height of the button is only `line-height: 1;`.  Taking padding into consideration, the height of `btn` should be at least `0.6*2+0.8=2em`. As a hack, change it to 3 will make it looks better. 

Normally, there will be a `<br>` before the button which solved this issue. But if there is summary metadate specified in an article e.g.
```md
summary: This a summary
```
there will not be no such a `<br>`. 

I am not familiar with css. And I don't know whether this is a bug of `flex` or `pelican`. It is wired that automatic summary is different from manually specified summary in metadata.

I love Flex, thank you!
