### ISSUE TITLE
Justify text in the articles

### ISSUE THREAD

**Issue by sebalix** [alexandrevicenzi/Flex#11]
Hi,

Is it possible to justify text in articles?
I added the following custom CSS:
```css
article p {
  text-align: justify;
}
```
But is there any drawback to do so, and if not maybe include it by default?
